name: CLI container-less on Mac

inputs:
  tier:
    description: |
      Test TIER name
    required: false
    type: string
    default: TIER0
  maven_token:
    description: |
      Token for public github maven repo access
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      distribution: 'microsoft'
      java-version: '21'
  - name: Setup Homebrew
    uses: Homebrew/actions/setup-homebrew@master
  - name: Install required tools
    shell: bash
    run: |
      ulimit -n unlimited
      brew install findutils gsed

  - name: Get kantra bundle
    uses: actions/download-artifact@v4
    with:
      name: kantra-bundle-arm64
      path: /Users/runner/.kantra

  - name: Configure Test Environment
    shell: bash
    run: |
      chmod +x /Users/runner/.kantra/darwin-kantra
      ln -s /Users/runner/.kantra /Users/runner/.config/.kantra
      mkdir ${{ github.workspace }}/report
    working-directory: ${{ github.workspace }}
  - name: Install test dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run TIER0 analysis test
    uses: nick-fields/retry@v3
    with:
      timeout_minutes: 20
      max_attempts: 3
      shell: bash
      command: |
        export PATH=$(brew --prefix)/opt/findutils/libexec/gnubin:$PATH
        export KANTRA_CLI_PATH=/Users/runner/.kantra/darwin-kantra
        export REPORT_OUTPUT_PATH=${{ github.workspace }}/report
        export PROJECT_PATH=${{ github.workspace }}
        export GIT_PASSWORD=${{ inputs.maven_token }}

        pytest -s tests/analysis/java/test_tier0.py

  - name: Save analysis output
    uses: actions/upload-artifact@v4
    if: always()
    with:
      name: kantra-outputs-mac-containerless
      path: ${{ github.workspace }}/report
