name: CLI container-less on Windows

inputs:
  tag:
    description: |
      Tag release
    required: false
    type: string
    default: latest
  tier:
    description: |
      Test TIER name
    required: false
    type: string
    default: TIER0

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      distribution: 'microsoft'
      java-version: '21'
  - run: java --version
    shell: cmd
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'
  - run: python -m pip install --upgrade pip
    shell: cmd
  - name: Set up Igor's kantra installer
    shell: cmd
    run: |
      git clone https://github.com/ibragins/konveyor-cli-deployment.git
      cd konveyor-cli-deployment
      pip install -r requirements.txt
      REM Error parsing json, trying just dummy example file, might be OK for upstream
      cp config.json.example config.json
      REM TODO: Use ${{ inputs.tag }} to specify required kantra version
      python install_cli.py --upstream true
      C:\Users\runneradmin\.kantra\windows-kantra.exe --help

  - name: Configure Test Environment Variables
    shell: cmd
    run: |
      cp .env.example .env
      
      echo "KANTRA_CLI_PATH=C:\Users\runneradmin\.kantra\windows-kantra.exe" >> .env
      echo "REPORT_OUTPUT_PATH=${{ github.workspace }}\report" >> .env
      echo "PROJECT_PATH=${{ github.workspace }}" >> .env
      REM # Set test tier to ENV variable (could be changed)
      set ${{ inputs.tier }}=1
    working-directory: ${{ github.workspace }}
  - name: Install test dependencies
    shell: cmd
    run: |
      pip install -r requirements.txt
      mkdir ${{ github.workspace }}\report

  # TODO: Run test for TIER0
  - name: Run simple standard analysis test
    shell: cmd
    run: |
      pytest -s -k "jee_example_app and not bug"

  - name: Save analysis output
    uses: actions/upload-artifact@v4
    with:
      name: kantra-outputs
      path: ${{ github.workspace }}\report
