name: CLI container-less on Windows

on:
  workflow_call:
    inputs:
      tag:
        description: |
          Tag release
        required: false
        type: string
        default: latest
      tier:
        description: |
          Test TIER name
        required: false
        type: string
        default: TIER0

jobs:
  windows-containerless:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '21'
    - run: java --version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: python -m pip install --upgrade pip

    - name: Set up Igor's kantra installer
      run: |
        git clone https://github.com/ibragins/konveyor-cli-deployment.git
        cd konveyor-cli-deployment
        pip install -r requirements.txt

        # Error parsing json, trying just dummy example file, might be OK for upstream
        cp config.json.example config.json

        # TODO: Use ${{ inputs.tag }} to specify required kantra version
        python install_cli.py --upstream true
        C:\Users\runneradmin\.kantra --help

    - name: Configure Test Environment Variables
      run: |
        cp .env.example .env
        
        echo "KANTRA_CLI_PATH=C:\Users\runneradmin\.kantra" >> .env
        echo "REPORT_OUTPUT_PATH=${{ github.workspace }}\report" >> .env
        echo "PROJECT_PATH=${{ github.workspace }}" >> .env

        # Set test tier to ENV variable (could be changed)
        set ${{ inputs.tier }}=1
      working-directory: ${{ github.workspace }}

    - name: Install test dependencies
      run: |
        pip install -r requirements.txt
        mkdir ${{ github.workspace }}\report

    - name: Run transform tests
      run: |
        pytest -s -k "transform and not bug"

    - name: Run common option tests
      run: |
        pytest -s -k "common and not bug"

    - name: Run advanced option tests
      run: |
        pytest -k "advanced and not bug"

    - name: Run simple standard analysis test
      run: |
        pytest -s -k "jee_example_app and not bug"

    - name: Save analysis output
      uses: actions/upload-artifact@v4
      with:
        name: kantra-outputs
        path: ${{ github.workspace }}\report
