name: CLI container-less on Linux

inputs:
  tag:
    description: |
      Tag release
    required: false
    type: string
    default: latest
  tier:
    description: |
      Test TIER name
    required: false
    type: string
    default: TIER0

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      distribution: 'microsoft'
      java-version: '21'
  - run: java --version
    shell: bash
  - name: Set up Igor's kantra installer
    shell: bash
    run: |
      git clone https://github.com/ibragins/konveyor-cli-deployment.git
      cd konveyor-cli-deployment
      pip install -r requirements.txt
      echo '{"misc_downstream_path": "","temp_dir": "","extract_binary": "","get_images_output": "","bundle": "","no_brew": "","ssh_user": "","ssh_key": ""}' >> config.json
      # Workaround ruleset home (?)
      mkdir -p /home/runner/.config
      ./install_cli.py --upstream true
      cd ..
      chmod +x /home/runner/.kantra/kantra
      /home/runner/.kantra/kantra --help

  - name: Configure Test Environment Variables
    shell: bash
    run: |
      cp .env.example .env
      mkdir ${{ github.workspace }}/report
      
      > .env
      echo "KANTRA_CLI_PATH=/home/runner/.kantra/kantra" >> .env
      echo "REPORT_OUTPUT_PATH=${{ github.workspace }}/report" >> .env
      echo "PROJECT_PATH=${{ github.workspace }}" >> .env
      
      cat .env
      # Set test tier to ENV variable (could be changed)
      export ${{ inputs.tier }}=1
    working-directory: ${{ github.workspace }}
  - name: Install test dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  # TODO: Run test for TIER0
  - name: Run simple standard analysis test
    shell: bash
    run: |
      pytest -s -k "jee_example_app and not bug"

  - name: Save analysis output
    uses: actions/upload-artifact@v4
    with:
      name: kantra-outputs
      path: ${{ github.workspace }}/report
