name: CLI containes on Linux

inputs:
  tier:
    description: |
      Test TIER name
    required: false
    type: string
    default: TIER0
  maven_token:
    description: |
      Token for public github maven repo access
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Setup Homebrew
    uses: Homebrew/actions/setup-homebrew@master
  - name: Install podman
    shell: bash
    run: |
      sudo apt install -y podman
      podman --version

  - name: Get kantra bundle
    uses: actions/download-artifact@v4
    with:
      name: kantra-bundle
      path: /home/runner/.kantra

  - name: Configure Test Environment
    shell: bash
    run: |
      chmod +x /home/runner/.kantra/kantra
      mkdir ${{ github.workspace }}/report
      # Temporary dirty workaround to execute container kantra (with run-local=false)
      sed -i 's/ analyze / analyze --run-local=false /g' utils/command.py 
    working-directory: ${{ github.workspace }}
  - name: Install test dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run TIER0 analysis test
    uses: nick-fields/retry@v3
    with:
      timeout_minutes: 20
      max_attempts: 3
      shell: bash
      command: |
        export KANTRA_CLI_PATH=/home/runner/.kantra/kantra
        export REPORT_OUTPUT_PATH=${{ github.workspace }}/report
        export PROJECT_PATH=${{ github.workspace }}
        export GIT_PASSWORD=${{ inputs.maven_token }}

        pytest -s tests/analysis/java/test_tier0.py

  - name: Save analysis output
    uses: actions/upload-artifact@v4
    if: always()
    with:
      name: kantra-outputs-linux-containers
      path: ${{ github.workspace }}/report
