name: CLI containes on Linux

inputs:
  tag:
    description: |
      Tag release
    required: false
    type: string
    default: latest
  tier:
    description: |
      Test TIER name
    required: false
    type: string
    default: TIER0

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Setup Homebrew
    uses: Homebrew/actions/setup-homebrew@master
  - name: Install podman
    shell: bash
    run: |
      sudo apt install -y podman
      podman --version
  - name: Set up Igor's kantra installer
    shell: bash
    run: |
      git clone https://github.com/ibragins/konveyor-cli-deployment.git
      cd konveyor-cli-deployment
      pip install -r requirements.txt
      echo '{"misc_downstream_path": "","temp_dir": "","extract_binary": "","get_images_output": "","bundle": "","no_brew": "","ssh_user": "","ssh_key": ""}' >> config.json
      # Workaround ruleset home (?)
      mkdir -p /home/runner/.config
      ./install_cli.py --upstream true
      cd ..
      chmod +x /home/runner/.kantra/kantra
      /home/runner/.kantra/kantra --help

  - name: Configure Test Environment Variables
    shell: bash
    run: |
      cp .env.example .env
      mkdir ${{ github.workspace }}/report
      
      > .env
      echo "export KANTRA_CLI_PATH=/home/runner/.kantra/kantra" >> .env
      echo "export REPORT_OUTPUT_PATH=${{ github.workspace }}/report" >> .env
      echo "export PROJECT_PATH=${{ github.workspace }}" >> .env
      
      cat .env
      # Set test tier to ENV variable (could be changed)
      export ${{ inputs.tier }}=1

      # Temporary dirty workaround to execute container kantra (with run-local=false)
      sed -i 's/ analyze / analyze --run-local=false /g' utils/command.py 
    working-directory: ${{ github.workspace }}
  - name: Install test dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run TIER0 analysis test
    shell: bash
    run: |
      . ${{ github.workspace }}/.env
      pytest -s tests/analysis/java/test_tier0.py

  - name: Save analysis output
    uses: actions/upload-artifact@v4
    if: always()
    with:
      name: kantra-outputs-linux-containers
      path: ${{ github.workspace }}/report
