name: Nightly CLI test for main

on:
  schedule:
    - cron: '08 1,13 * * *'

jobs:
  test-suite:
    uses: konveyor-ecosystem/kantra-cli-tests/.github/workflows/test-suite.yaml@main
    secrets: inherit
    with:
      tag: latest
      tests_ref: main
      tier: TIER0
