name: Nightly CLI test for release-0.6

on:
  schedule:
    - cron: '08 1,13 * * *'

jobs:
  test-suite:
    uses: konveyor-ecosystem/kantra-cli-tests/.github/workflows/test-suite.yaml@main # TODO: a corresponding kantra-cli-tests branch will be needed with next releases
    secrets: inherit
    with:
      tag: release-0.6
      tier: TIER0
  report_failure:
    needs: test-suite
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "test": "CLI kantra",
              "branch": "release-0.6",
              "note": "Failed run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
