name: Nightly CLI test suite for main branch and latest kantra

on:
  schedule:
    - cron: '12 1,13 * * *'

jobs:
  test-suite:
    uses: aufi/kantra-cli-tests/.github/workflows/test-suite.yaml@basic-workflows # Replace with konveyor-ecosystem (cannot do checkout before for different OSs)
    with:
      tag: latest
      tier: TIER0
