name: Nightly CLI test for release-0.7

on:
  schedule:
    - cron: '14 1,13 * * *'

jobs:
  test-suite:
    uses: konveyor-ecosystem/kantra-cli-tests/.github/workflows/test-suite.yaml@main # TODO: a corresponding kantra-cli-tests branch will be needed with next releases
    secrets: inherit
    with:
      tag: release-0.7
      tier: TIER0
