name: PR/push CLI tests for main

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  test-suite:
    uses: aufi/kantra-cli-tests/.github/workflows/test-suite.yaml@basic-workflows # Replace with konveyor-ecosystem (cannot do checkout before for different OSs)
    with:
      tag: latest
      tier: TIER0
