name: PR/push CLI tests for main

on:
  pull_request_target:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  test-suite:
    uses: konveyor-ecosystem/kantra-cli-tests/.github/workflows/test-suite.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      tag: latest
      tier: TIER0
