name: PR/push CLI tests for main

on:
  pull_request_target:
    branches: [ "*" ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  test-suite:
    uses: aufi/kantra-cli-tests/.github/workflows/test-suite.yaml@tier0-fix-pathlib-windows
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      tag: latest
      tier: TIER0
      tests_ref: ${{ github.event.pull_request.merge_commit_sha }}
