name: CLI test suite

on:
  workflow_call:
    inputs:
      tag:
        description: |
          Tag release
        required: false
        type: string
        default: latest
      tier:
        description: |
          Test TIER name
        required: false
        type: string
        default: TIER0

jobs:
  bundle-kantra:
    runs-on: ubuntu-latest
    steps:
    - name: Extract kantra files from images
      shell: bash
      run: |
        export KANTRA_DIR=.kantra
        mkdir $KANTRA_DIR
        docker create --name kantra-download quay.io/konveyor/kantra:${{ inputs.tag }}
        docker cp kantra-download:/usr/local/bin/kantra $KANTRA_DIR/kantra
        docker cp kantra-download:/usr/local/bin/windows-kantra $KANTRA_DIR/windows-kantra.exe
        docker cp kantra-download:/usr/local/bin/darwin-kantra $KANTRA_DIR/darwin-kantra
        docker cp kantra-download:/jdtls $KANTRA_DIR/jdtls
        docker cp kantra-download:/bin/fernflower.jar $KANTRA_DIR/fernflower.jar
        docker cp kantra-download:/usr/local/static-report $KANTRA_DIR/static-report
        docker cp kantra-download:/opt/rulesets $KANTRA_DIR/rulesets
        docker cp kantra-download:/usr/local/etc/maven.default.index $KANTRA_DIR/maven.default.index
        ls -l $KANTRA_DIR
        chmod +x $KANTRA_DIR/kantra
        chmod +x $KANTRA_DIR/darwin-kantra
    - uses: actions/upload-artifact@v4
      with:
        name: kantra-bundle
        path: .kantra

  tests-windows-containerless:
    runs-on: windows-latest
    needs: bundle-kantra
    steps:
    - uses: actions/checkout@v4
    - name: Windows container-less tests
      uses: ./.github/actions/tests-windows-containerless
      with:
        tag: ${{ inputs.tag }}
        tier: ${{ inputs.tier }}

  tests-linux-containerless:
    runs-on: ubuntu-latest
    needs: bundle-kantra
    steps:
    - uses: actions/checkout@v4
    - name: Linux container-less tests
      uses: ./.github/actions/tests-linux-containerless
      with:
        tag: ${{ inputs.tag }}
        tier: ${{ inputs.tier }}


  tests-linux-containers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Linux containers tests
      uses: ./.github/actions/tests-linux-containers
      with:
        tag: ${{ inputs.tag }}
        tier: ${{ inputs.tier }}
